{{- if not .Values.secret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rustfs.secretName" . }}
  namespace: {{ include "rustfs.namespace" . }}
  labels:
    {{- include "rustfs.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data:
  RUSTFS_ACCESS_KEY: {{ required "secret.accessKey is required. Set rustfs.secret.accessKey or provide rustfs.secret.existingSecret." .Values.secret.accessKey | b64enc | quote }}
  RUSTFS_SECRET_KEY: {{ required "secret.secretKey is required. Set rustfs.secret.secretKey or provide rustfs.secret.existingSecret." .Values.secret.secretKey | b64enc | quote }}
{{- end }}

---
{{- if .Values.imageRegistryCredentials.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rustfs.imagePullSecret.name" . }}
  namespace: {{ include "rustfs.namespace" . }}
  labels:
    {{- toYaml .Values.commonLabels | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
